### PR TITLE
new file

### PR DESCRIPTION
**Pull request by zegnus**
Do not merge

### CODE REVIEW

**Comment by blundell** [comment]
retest this please

**Comment by blundell** [comment]
retest this please

**Comment by blundell** [comment]
test this

**Comment by blundell** [comment]
test this

**Comment by blundell** [comment]
test this

**Comment by blundell** [comment]
test this

**Comment by blundell** [comment]
test this

**Comment by blundell** [comment]
test this

**Comment by hal9002** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.novoda.com/job/dojos-prb/9/
Test PASSed.

**Pull request closed without merging**
